name: Actions@api

on:
  push:
    branches:
      - master
      - fix/api-deploy-to-heroku
    # paths:
    #   - "api/**"

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build
        working-directory: ./api
        run: |
          yarn install
          yarn test
          yarn build

      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login

      - name: Push to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:push -a jovertpalonpon web --workdir api

      - name: Release from Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a jovertpalonpon web
