name: Actions@api

on:
  push:
    branches:
      - master
    paths:
      - "api/**"

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Move files to root
        run: cp -r api/. . && rm -r api site dashboard

      - name: Install dependencies
        run: npm install

      - name: Run the test suite
        run: ./node_modules/.bin/jest

      - name: Run code quality checks
        run: npm run --silent lint

      - name: Run production build
        run: npm run build

      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login

      - name: Push to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:push -a palonponjovertlota web

      - name: Release from Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a palonponjovertlota web
