name: Client

on:
  push:
    branches:
      - master
      - "*" # remove this later
    paths:
    - 'client/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node.js dependencies
        run: npm install

      - name: Run code quality checks
        uses: stefanoeb/eslint-action@master
        with:
          args: --ext .ts,.tsx .