name: Actions

on:
  push:
    branches:
      - feat/deploy-to-zeit
      - '!master'

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build
        run: |
          yarn install
          yarn test

      - name: Deploy
        run: ./node_modules/.bin/now --prod --token=${{ secrets.ZEIT_TOKEN }}
