name: Actions@site

on:
  push:
    branches:
      - master
      - '*' #remove this later
    # paths:
    # - 'site/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Node.js dependencies
        run: npm install --prefix=./site

      - name: Run code quality checks
        run: npm run --prefix=./site --silent lint

      - name: Run production build
        run: npm run --prefix=./site export

      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.SITE_NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_NETLIFY_API_ID }}
        with:
          args: publish
